name: Hollis
favicon: null
layout_spectrum: 0.61923
typography_spectrum: 0.8620755490846932
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#decfc8'
    - '#f5f3f4'
    - '#ac9d7c'
    - '#b16924'
    - '#211811'
  brandStrength: 0.5103222685866058
  lightness: 0.22529373154975474
  saturation: 0.6976559816394001
  rhythmicContrast: 0.16817772388458252
purpose: []
